### ISSUE TITLE
Users are registering with spaces in their username.

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#11]
Some users have been registering with "firstname lastname" as their username. 

While technically possible (http://xmpp.org/extensions/xep-0106.html#examples-xmpp), it breaks a lot of assumptions on how the system works with things like @username quoting.

We should show a warning if they try to register with a space in their username.

**Comment by lloydwatkin** [comment]
Fixed in https://github.com/project-isizwe/wifi-chat/commit/a621ea129bbcd01384598ae7d827728132e941fd, released in 1.1.1
