### ISSUE TITLE
Repeating topics.

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#12]
From Natalie.

"Hey, something we are noticing on our phones is that topics are being repeated and then when you refresh it goes back to one again. 

It hasn’t happened on my PC yet though. Any idea what thats about?"

I'm also noticing it on my phone.

**Comment by lloydwatkin** [comment]
Replication steps:
- Navigate to a channel
- Navigate to view comments for a topic
- Hit the back button

**Comment by lloydwatkin** [comment]
I can also replicate this on desktop

**Comment by lloydwatkin** [comment]
This is interesting, the problem doesn't exist on returning to the page but as soon as any scrolling event takes place it attempts to load more posts and additional posts are then displayed.
