### ISSUE TITLE
Daily report on user numbers

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#13]
@Natalieprojectisizwe wants a way to see daily user numbers - emailed to her.

Also top posters emailed to her.

Also include a dump of all emails.

**Comment by lloydwatkin** [comment]
This is more than likely functionality we need to build into the server rather than the project itself (unless we decide to expose the data via the UI).

I'd potentially suggest a new reporting component which can pull data from the database (so as not to pollute the main buddycloud server functionality). Itself either posting back to a channel, sending an email, sending data to some other metrics system.

**Comment by imaginator** [comment]
This was me making notes on stuff that I can sort out with a cron-job
today. At least to start getting metrics before a
super-awesome-metrics-dashboard project.

On 20 May 2015 at 10:46, Lloyd Watkin notifications@github.com wrote:

> This is more than likely functionality we need to build into the server
> rather than the project itself (unless we decide to expose the data via the
> UI).
> 
> I'd potentially suggest a new reporting component which can pull data from
> the database (so as not to pollute the main buddycloud server
> functionality). Itself either posting back to a channel, sending an email,
> sending data to some other metrics system.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/project-isizwe/wifi-chat/issues/13#issuecomment-103813039
> .

## 

Simon Tennant | CEO Buddycloud http://buddycloud.com | +49 17 8545 0880

**Comment by imaginator** [comment]
@Natalieprojectisizwe you should start receiving these tomorrow morning and every morning just after 6am. 

I've tested the report with my own address. And will check that it goes out in the morning. For now, I'm closing this issue off.

**Comment by Natalieprojectisizwe** [comment]
Thanks for the daily update emails. One thing though, is it all possible to get both the email addresses as well as the usernames used to signup? Its impossible to track down winners by their usernames because their signup email address is not attached in the admin interface.

**Comment by imaginator** [comment]
fixed in the other issue. Yes - you should be getting both from tomorrow.
