### ISSUE TITLE
Add email disclaimer

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#15]
We’ve been having some issues in sending welcome emails to everyone who has signed up using MailChimp because users haven’t given us permission to send them emails. Please add the following to the rules disclaimer that all users can see upon signup:

*By clicking ‘Start using WiFi Chat’ you also agree to receiving regular updates from the WiFi Chat team sent to the email address used to create your account.

**Comment by mrflix** [comment]
Added in ca8f00ed07f8bc9ebafbf7e39d7e7cacbfc3c549
