### ISSUE TITLE
Admin links need to be clickable

### ISSUE THREAD

**Issue by Natalieprojectisizwe** [project-isizwe/wifi-chat#16]
As admin I should be able to share links in comments should users have questions. I’ve just tried to share a link and it is not clickable. Is this possible? I'm not sure users should be able to share links yet to avoid dodgy stuff being shared.

**Comment by mrflix** [comment]
Allowing everyone to comment with clickable links would be the easiest solution.
I'm looking into the feasibility of restricting this ability to admins with Lloyd.

**Comment by Natalieprojectisizwe** [comment]
Im open to ideas. Maybe its not that awful allowing link sharing

**Comment by mrflix** [comment]
Right now we parse the following:
- Images
- Links
- WiFi-TV Videos

I think it should be done all or nothing: allow everyone to comment with these kinds of things, not just admins. Since we have blocking and post deletion we can get rid of bad posts/users.

**Comment by lloydwatkin** [comment]
Ahh, now I see the context of your question @mrflix. What I mentioned was the user's affiliation, not the publishers.

We could achieve this by grabbing a list of the affiliations for the node and then seeing what affiliation the publisher has. The problem with this is that when the number of subscribers becomes large then you're looking at pulling an awful lot of information down for very little reward.

What we could do is extend the affiliations/subscription retrieval method on the server such that we can ask for users that have a specific affiliation (in this case we'd need to make two requests, moderators and owners) but that would give a much smaller list to work with.

I'd suggest we go with parsing links for everyone and then see how much it gets abused (after all admins can delete and ban a user if they misuse the system). It would seem the most sensible short term approach at least, especially as users will probably want to help each other out with external links.

**Comment by lloydwatkin** [comment]
...and not that it really matters in this case but I think adding `rel="nofollow"` for future **smarter** browsers would be a good idea on all user posted links.

**Comment by mrflix** [comment]
`rel="nofollow"` is already in there https://github.com/project-isizwe/wifi-chat/blob/master/public/scripts/app/models/Post.js#L41

**Comment by lloydwatkin** [comment]
:+1:

**Comment by Natalieprojectisizwe** [comment]
When can we resolve this? I have a number questions I'd like to answer and include links to websites to help users

**Comment by mrflix** [comment]
Nathalie, we answered with suggestions and wait for you to make a decision if we should go the easy way and enable it for everyone or go the hard way and enable it just for the admin account.

**Comment by Natalieprojectisizwe** [comment]
I think we need to go the hard way. I cant moderate all links without filters at this point.

**Comment by mrflix** [comment]
@lloydwatkin how about a whitelist of user-ids (jids) who's comments should get parsed?
@Natalieprojectisizwe right now it only concerns the admin account, right?

**Comment by Natalieprojectisizwe** [comment]
@mrflix yes

**Comment by lloydwatkin** [comment]
@mrflix that would be a quick way of solving the issue but its very lazy. I'd certainly be for putting that in place (in the config) for the short term and then coding it up properly in the server for the longer term - since moderators/owners will be different for each channel eventually I'd assume @Natalieprojectisizwe?

**Comment by lloydwatkin** [comment]
Ref: https://github.com/buddycloud/buddycloud-server-java/issues/309

**Comment by Natalieprojectisizwe** [comment]
@lloydwatkin yes. Eventually we'd want moderators to be able to respond using links as well

**Comment by Natalieprojectisizwe** [comment]
Just checking in on where we stand in getting admin to be able to post links in comments?

**Comment by mrflix** [comment]
Hey Natalie. So I went the easy way and manually activated the link parsing for the admin@projectisizwe.org account!

**Comment by Natalieprojectisizwe** [comment]
Thanks so much
