### ISSUE TITLE
Daily automated email 

### ISSUE THREAD

**Issue by Natalieprojectisizwe** [project-isizwe/wifi-chat#17]
Hi there
We need the daily automated email to show email addresses as well as the associated usernames if at all possible. We are currently running a competition where we will need to contact the winner via email but have no way to match the username to email addresses.

Is this possible?

**Comment by lloydwatkin** [comment]
This information lives in a separate database but there's no reason it can't be pulled out for you. @imaginator will be the one who can implement on the server for you :)

**Comment by imaginator** [comment]
@Natalieprojectisizwe this is now done. 

The next email should include the username and email data in it.
