### ISSUE TITLE
text fixes

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#22]
Just had a call with Tim
- Rubbish => Refuse
- Lightning => Lighting

**Comment by mrflix** [comment]
the categories i'm sending are:
- refuse 
- lighting
- robots
- wifi
- road
- signs
- park
- emergency
- street_furniture
- other

@retrobunny do you have to adjust something on the backend for the name changes to work?

**Comment by lloydwatkin** [comment]
The only backend change required would be if we added/changed any category fields (here: https://github.com/project-isizwe/wifi-chat/blob/3152d2cd1f2f34eb66ed53a8e6a82039fef336a7/src/fault.js#L41-L44)

**Comment by mrflix** [comment]
allright, good to know. Didn't happen.
