### ISSUE TITLE
Wrong GitHub links in project.json

### ISSUE THREAD

**Issue by ChALkeR** [project-isizwe/wifi-chat#30]
See https://www.npmjs.com/package/isizwe-wifi-chat.

[package.json#L12](https://github.com/project-isizwe/wifi-chat/blob/v1.1.1/package.json#L12), [package.json#L24](https://github.com/project-isizwe/wifi-chat/blob/v1.1.1/package.json#L24).

**Comment by lloydwatkin** [comment]
Thanks fixed in 985a54b9a4e67d3251f5699c4b8e1b613ba96bc9

However this should not be in npm as far as I understand it @imaginator ?

**Update:** Looks like the idiot who published this was me, muscle memory. Will unpublish this evening.
