### ISSUE TITLE
Display name change vs username.

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#4]
Setting the name probably works – we just don't display the name, just the username. 

This to be added to the post model and all views where it's needed.

On topics show display when set, otherwise just username. 

Same goes for user profile. In a comment only show one of the the two: when the displayName is set, show it, otherwise display the username.

@Natalieprojectisizwe: how do you want to handle this?

**Comment by mrflix** [comment]
Yeah, we have to fix that

**Comment by lloydwatkin** [comment]
Locations for implementation:
- [x] Topic list
- [x] Comments
- [x] Topics header
- [x] Comments header
- [x] Push channel loading down into the collection too
