### ISSUE TITLE
Show Context - change up to 20 posts

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#5]
I just saw that we only display 5 comments at a time – that low number comes from debugging – we should raise it at least to 20. Same goes for last displayed topics. ( @lloydwatkin / @mrflix I guess we need more content in the system to see the effects of this too)

**Comment by lloydwatkin** [comment]
Closing as @mrflix has fixed in cdb8ee937489104b29a0b56ef5d5bd1cf021abe3 (updated to 30 posts per load)

**Comment by imaginator** [comment]
Looking at this now  with Tim - it's pulling in more posts but we need a way to scroll to the yellow post. How possible is this?

**Comment by imaginator** [comment]
Closing for the moment.
