### ISSUE TITLE
Avatar updates

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#6]
I saw that bug on mobile: seems that we don't listen for avatar changes on our views. Or When I updated my avatar on mobile it only changed on my settings – nowhere else. 

Only after a reload of the app it displayed everywhere else. To force a new avatar load we might have to add a timestamp to the request url (as we did with the avatar in settings). I can take care of this. Will approx. take 2 hours.

**Comment by mrflix** [comment]
(Simon is citing me)

**Comment by imaginator** [comment]
If it fits I sitz^Wcitez

**Comment by mrflix** [comment]
- [x] create Avatar store
- [x] bind views to update avatar on url change
- [x] force image reload from the same url using the timestamp
- [x] make parameters work
- [x] render the avatar immediatelly if already loaded

**Comment by lloydwatkin** [comment]
:+1:

**Comment by imaginator** [comment]
:+1:
