### ISSUE TITLE
Odd formatting of reporting emails

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#8]
![screenshot_2015-04-17-16-32-24](https://cloud.githubusercontent.com/assets/469572/7216590/fd5fb4ae-e604-11e4-885c-a5307de353b6.png)

**Comment by lloydwatkin** [comment]
I'm seeing:

![screenshot from 2015-04-20 09 35 28](https://cloud.githubusercontent.com/assets/271622/7226438/a96d10e8-e740-11e4-8901-ccb1d2759f12.png)

**Comment by imaginator** [comment]
Looks good. Closing.

**Comment by imaginator** [comment]
felix just pointed out that I need another coffee. Reopening.

**Comment by lloydwatkin** [comment]
Me too.

However I've tested this on both the android mail app and the gmail app and everything appears normal. The mailto link is generated in the standard way. I don't have an iphone in order to test there, but I'm thinking this is an apple issue. Will see what I can find in google.

**Comment by mrflix** [comment]
That's not an iOS screenshot. Lloyd take a strong one 😆

**Comment by imaginator** [comment]
Same thing on Gmail.

**Comment by imaginator** [comment]
Tim says he tested in Gmail and Samsung mail app. I'm wondering if it's something related to:  http://stackoverflow.com/questions/12172338/android-email-replaces-space-with-plus

**Comment by lloydwatkin** [comment]
This is strange because I've done the same and can't replicate :( ...and if I can't replicate I can't fix.  Can you guys replicate at all?

**Comment by mrflix** [comment]
It appears to be a Android Mail bug: http://stackoverflow.com/questions/26380311/replace-with-space-in-html-gmail-android-chrome
There is no simple way to fix this. The good thing is it work in every email client except the native non gmail one. A fix would be to integrate the reporting into the app and send it via our server. The best user-experience would be to just click on report, confirm a popup and thats it. We'd have to limit reporting capabilities to prevent spamming.

**Comment by lloydwatkin** [comment]
Fixed as we now use the server to send reporting emails.
