### ISSUE TITLE
Empty profile from "My posts" screen.

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#9]
![screenshot 2015-04-21 11 18 54](https://cloud.githubusercontent.com/assets/469572/7249249/5a988234-e819-11e4-8715-458056c3732d.png)

Clicking on "You" takes one to an empty profile.

![screenshot 2015-04-21 11 29 36](https://cloud.githubusercontent.com/assets/469572/7249323/d727f1ea-e819-11e4-8edd-05e7ed75db21.png)

**Comment by lloydwatkin** [comment]
I'll take a look at it this morning.... actually just by looking at the URL I know that the issue is.
